# -*- coding: utf-8 -*-
"""kenpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCMA334FHzKUuZyYQ3QdqgYOAjI_McC6
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Colab Notebooks/kenpo/forms.xlsx'

form_names = list(pd.read_excel(file_path, sheet_name = None).keys())

forms = []
for i in form_names:
  forms.append(pd.read_excel(file_path, sheet_name = i))

ranks = []
for i in range(len(form_names)):
  for j in forms[i].Rank.dropna():
    ranks.append(j)
ranks = list(dict.fromkeys(ranks))
ranks.sort()

styles = []
for i in range(len(form_names)):
  for j in forms[i].Style.dropna():
    styles.append(j)
styles = list(dict.fromkeys(styles))
styles.sort()

punches = []
for i in range(len(form_names)):
  for j in forms[i].Punches.dropna():
    punches.append(j)
punches = list(dict.fromkeys(punches))
punches.sort()

kicks = []
for i in range(len(form_names)):
  for j in forms[i].Kicks.dropna():
    kicks.append(j)
kicks = list(dict.fromkeys(kicks))
kicks.sort()

import random

practice_forms = []

punch = random.choice(punches)
if punch in ['Front Two Knuckle','Back Two Knuckle','Thrust','Inverted Thrust','Hook','U']:
  print('Practice your',punch,'Punch by doing these forms:')
elif punch in ['Hon Tsuki','Snake']:
  print('Practice your',punch,'Strike by doing these forms:')
else:
  print('Practice your',punch,'by doing these forms:')
for i in range(len(form_names)):
  for j in forms[i].Punches:
    if j == punch:
      practice_forms.append(form_names[i])
      print(form_names[i])

kick = random.choice(kicks)
if kick in ['Rising Knee']:
  print('\nPractice your',kick,'by doing these forms:')
else:
  print('\nPractice your',kick,'Kick by doing these forms:')
for i in range(len(form_names)):
  for j in forms[i].Kicks:
    if j == kick:
      practice_forms.append(form_names[i])
      print(form_names[i])

rank = random.choice(ranks)
if rank in ['Beginner','Intermediate','Advanced','Sankyu','Nikkyu','Ikkyu','Shodan','Nidan']:
  print('\nPractice your',rank,'forms:')
else:
  print('\nPractice your',rank,'Belt forms:')
for i in range(len(form_names)):
  for j in forms[i].Rank:
    if j == rank:
      practice_forms.append(form_names[i])
      print(form_names[i])

style = random.choice(styles)
if style == 'Blocking':
  print('\nPractice your',style,'Systems:')
elif style in ['Fist Set','Kata','Pinian','Ning Li']:
  print('\nPractice your',style+'s:')
else:
  print('\nPractice your',style,'forms:')
for i in range(len(form_names)):
  for j in forms[i].Style:
    if j == style:
      practice_forms.append(form_names[i])
      print(form_names[i])

practice_forms = list(dict.fromkeys(practice_forms))
practice_forms.sort()
print('\nConcise List of Forms ('+str(len(practice_forms))+'):')
for i in practice_forms:
  print(i)